version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SUPERUSER_PASSWORD: "admin"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data:

